import { Brand, Cta, Icon, NfcCard, PhonePreview } from "./Visuals";
import { demos, faqs, navigation, packages } from "./content";
import styles from "./landing.module.css";

export function Hero() {
  return <section className={styles.hero} aria-labelledby="hero-title"><div className={styles.container + " " + styles.heroGrid}>
    <div className={styles.heroCopy}><p className={styles.eyebrow}>TAP. CONNECT. GROW.</p><h1 id="hero-title">One Tap.<br /><span>Infinite<br className={styles.desktopBreak} /> Opportunities.</span></h1><p className={styles.lead}>Your business, one connection away.</p><p className={styles.description}>An NFC card. A beautiful digital profile. Everything customers need — from your menu to your next review — in one simple tap.</p><div className={styles.actions}><Cta>Get Started</Cta><Cta secondary href="#how-it-works"><span aria-hidden="true">▷</span> See how it works</Cta></div><ul className={styles.heroBenefits}><li><Icon name="qr" />NFC &amp; QR</li><li><Icon name="profile" />Custom profiles</li><li><Icon name="growth" />Better connections</li></ul></div>
    <div className={styles.productStage}><div className={styles.orbit} aria-hidden="true" /><div className={styles.heroPhone}><PhonePreview demo={demos[0]} /></div><div className={styles.heroCard}><NfcCard /></div><div className={styles.tapLabel}><span className={styles.signalDot} />One tap. You’re connected.</div><p className={styles.visualCaption}>NFC CARD <span>→</span> DIGITAL PROFILE <span>→</span> NEXT CONNECTION</p></div>
  </div></section>;
}
export function Features() {
  const features = [{ icon: "qr", title: "NFC & QR ready", text: "One tap or scan. Straight to your business." }, { icon: "profile", title: "Made to be yours", text: "A digital profile with your business’s personality." }, { icon: "link", title: "All your links", text: "Your menu, socials, booking and reviews. Together." }, { icon: "growth", title: "Make connection easy", text: "Less searching. More ways to take the next step." }] as const;
  return <section id="features" className={styles.section}><div className={styles.container}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>BUILT FOR MODERN BUSINESSES</p><h2>Everything you need.<br />All in one link.</h2></div><p>A simple, considered home for your business online. Share what matters, and help every visitor find their next step.</p></div><div className={styles.featureGrid}>{features.map(item => <article className={styles.feature} key={item.title}><span className={styles.iconBox}><Icon name={item.icon} /></span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>;
}
export function ProfileShowcase() {
  const slug = process.env.NEXT_PUBLIC_DEMO_BUSINESS_SLUG;
  return <section id="examples" className={styles.section + " " + styles.showcase}><div className={styles.container}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>A PROFILE FOR YOUR KIND OF BUSINESS</p><h2>Different businesses.<br />Endless possibilities.</h2></div><div><p>From the first coffee to the last set. Make your business feel like your business.</p><p className={styles.finePrint}>Illustrative demo profiles, not customer endorsements.</p>{slug && <a className={styles.textLink} href={"/" + encodeURIComponent(slug)} target="_blank" rel="noopener noreferrer">Explore a live profile ↗</a>}</div></div><div className={styles.profileRail} tabIndex={0} role="region" aria-label="Example profiles. Scroll horizontally on smaller screens.">{demos.map(demo => <figure key={demo.name} className={styles.profileFigure}><PhonePreview demo={demo} /><figcaption><strong>{demo.category}</strong><span>{demo.name} · demo</span></figcaption></figure>)}</div><p className={styles.swipeHint}>Explore the profiles ↔</p></div></section>;
}
export function NfcShowcase() {
  return <section className={styles.section + " " + styles.nfcSection}><div className={styles.container + " " + styles.nfcGrid}><div className={styles.cardStage}><div className={styles.cardHalo} aria-hidden="true" /><NfcCard /><span className={styles.contactless} aria-hidden="true">)))</span><span className={styles.cardCaption}>PHYSICAL CARD. DIGITAL POSSIBILITIES.</span></div><div><p className={styles.eyebrow}>SMALL CARD. BIG POTENTIAL.</p><h2>A small card.<br />A big difference.</h2><p className={styles.description}>Make your introduction count. A professional NFC card connects the person in front of you with everything your business has to offer.</p><div className={styles.actions}><Cta>Get Your NFC Card</Cta><a className={styles.textLink} href="#how-it-works">Learn more ↗</a></div></div><ul className={styles.nfcBenefits}><li><Icon name="tap" /><div><strong>Instant connection</strong><span>Tap with a compatible phone.</span></div></li><li><Icon name="profile" /><div><strong>No app required</strong><span>Opens in the browser.</span></div></li><li><Icon name="link" /><div><strong>Always connected</strong><span>Update your profile, keep your card.</span></div></li><li><Icon name="qr" /><div><strong>More than one way in</strong><span>Tap with NFC or scan a QR code.</span></div></li></ul></div></section>;
}
export function HowItWorks() {
  return <section id="how-it-works" className={styles.section}><div className={styles.container}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>FROM HELLO TO CONNECTED</p><h2>Three steps. One simple tap.</h2></div><p>We help you get set up. Your customers get a simpler way to find you.</p></div><ol className={styles.steps}>{[{ title: "Create your profile", text: "Bring your information, links, menu and branding together." }, { title: "Connect your card", text: "Your NFC card links directly to your digital business profile." }, { title: "Tap. Open. Connect.", text: "Customers tap or scan, open your profile and choose what’s next." }].map((step, i) => <li key={step.title}><span className={styles.stepNumber}>0{i + 1}</span><h3>{step.title}</h3><p>{step.text}</p></li>)}</ol></div></section>;
}
export function Pricing() {
  return <section id="pricing" className={styles.section + " " + styles.pricing}><div className={styles.container + " " + styles.pricingGrid}><div><p className={styles.eyebrow}>A SIMPLE PLACE TO START</p><h2>Your next connection<br />starts here.</h2><p className={styles.description}>Tell us about your business. We’ll help you choose the right setup and confirm the price before you order.</p><p className={styles.finePrint}>Need cards for a team or more than one location? Include that in your inquiry.</p></div>{packages.map(plan => <article className={styles.priceCard} key={plan.name}><p className={styles.eyebrow}>{plan.label}</p><h3>{plan.name}</h3><p className={styles.price}>{plan.price}</p><p>{plan.description}</p><ul>{plan.included.map(item => <li key={item}><Icon name="check" />{item}</li>)}</ul><Cta>Request pricing</Cta><span className={styles.finePrint}>An inquiry, not a checkout. No payment required.</span></article>)}</div></section>;
}
export function SocialProof() {
  // Replace with approved customer stories when available; never invent reviews.
  return <section id="about" className={styles.section}><div className={styles.container + " " + styles.proofGrid}><div><p className={styles.eyebrow}>BUILT AROUND REAL CONNECTIONS</p><h2>Less friction.<br />More possibility.</h2></div><div className={styles.proofStatement}><span className={styles.quoteMark} aria-hidden="true">↗</span><p>Your next regular. Your next booking. Your next conversation.</p><span>Give people a direct path from meeting your business to connecting with it.</span></div></div></section>;
}
export function Faq() {
  return <section id="faq" className={styles.section}><div className={styles.container + " " + styles.faqGrid}><div><p className={styles.eyebrow}>GOT QUESTIONS?</p><h2>Good questions.<br />Simple answers.</h2><p className={styles.description}>Get to know your next connection.</p><a className={styles.textLink} href="/get-started">Ask us something else ↗</a></div><div className={styles.faqList}>{faqs.map(faq => <details key={faq.question}><summary>{faq.question}<span aria-hidden="true">+</span></summary><p>{faq.answer}</p></details>)}</div></div></section>;
}
export function FinalCta() {
  return <section id="contact" className={styles.finalCta}><div className={styles.container}><p className={styles.eyebrow}>READY FOR YOUR NEXT CONNECTION?</p><h2>Turn every tap<br />into a <span>possibility.</span></h2><div className={styles.actions}><Cta>Get Started</Cta><Cta href="/get-started" secondary>Contact Us</Cta></div></div></section>;
}
export function MarketingFooter() {
  return <footer className={styles.footer}><div className={styles.container}><div className={styles.footerGrid}><div><a href="#home" aria-label="AuraLink home"><Brand /></a><p>Tap. Connect. Grow.</p><span>Your business, beautifully connected.</span></div><div><h3>Explore</h3>{navigation.filter(item => item.label !== "Home").map(item => <a key={item.href} href={item.href}>{item.label}</a>)}</div><div><h3>AuraLink</h3><a href="#about">About</a><a href="/get-started">Contact</a><a href="/admin/login">Login</a></div><div className={styles.footerNote}><h3>Let’s build your connection.</h3><p>Have a question about cards, profiles or getting started? We’re here to help.</p><a className={styles.textLink} href="/get-started">Start a conversation ↗</a></div></div><div className={styles.footerBottom}><span>© {new Date().getFullYear()} AuraLink. All rights reserved.</span><span>One card. A world of connections.</span></div></div></footer>;
}
