import {expect,it} from "vitest";
import {resolveProfileBackground,profilePresentation,backgroundPresets} from "@/lib/profile-presentation";
import {profileDesign} from "@/lib/profile-design";
import {profilePresets,applyProfilePreset} from "@/lib/profile-presets";
const profile={backgroundType:"SOLID" as const,backgroundColor:null,backgroundGradient:null,backgroundImageUrl:null,backgroundMode:"LIGHT" as const};
it("explicit white owns page paint even with saved PEARL",()=>{const d=profileDesign.parse({backgroundPreset:"PEARL",visual:{version:1,canvas:{background:"SOLID",color:"#ffffff"}}});expect(resolveProfileBackground(profile,d).style).toMatchObject({backgroundColor:"#ffffff",backgroundImage:"none"});expect(resolveProfileBackground(profile,d).style).not.toHaveProperty("background");expect(profilePresentation(d,false)).not.toHaveProperty("background");expect(d.backgroundPreset).toBe("PEARL")});
it("keeps Current and legacy backgrounds intact",()=>{expect(resolveProfileBackground(profile,profileDesign.parse({backgroundPreset:"PEARL",visual:{version:1,canvas:{background:"EXISTING"}}})).style).toEqual({background:backgroundPresets.PEARL});expect(resolveProfileBackground(profile).style).toEqual({backgroundColor:"#F7F7F8"})});
it("retained legacy defaults cannot change explicit dark canvas appearance",()=>{expect(resolveProfileBackground(profile,profileDesign.parse({backgroundPreset:"PEARL",visual:{version:1,canvas:{background:"SOLID",color:"#101518",appearance:"DARK"}}})).mode).toBe("dark")});
it("all six supported compositions reset without discarding content",()=>{expect(profilePresets).toHaveLength(6);for(const p of profilePresets){const next=applyProfilePreset(profileDesign.parse({backgroundPreset:"PEARL",footer:{text:"Keep footer"},visual:{version:1,hero:{tagline:"Keep tagline",showBusinessType:false},canvas:{color:"#123456"}}}),p.visual);expect(next.visual?.canvas).toEqual(p.visual.canvas);expect(next.visual?.hero).toMatchObject({tagline:"Keep tagline",showBusinessType:false});expect(next.footer?.text).toBe("Keep footer");expect(resolveProfileBackground(profile,next).style).not.toHaveProperty("background");expect(next.visual?.socials?.action?.iconColor).toBeTruthy()}});
