import {profileVisual,type ProfileVisual} from "./profile-visual";
import type {ProfileDesign} from "./profile-design";

// A preset is a starting configuration, never a renderer identity. Keep this
// catalogue small. Content, uploaded photos, section order and overrides survive.
const preset=(name:string,visual:ProfileVisual)=>({name,visual:profileVisual.parse(visual)});
export const profilePresets=[
  preset("Modern Minimal",{"version":1,"canvas":{"background":"SOLID","color":"#ffffff","appearance":"LIGHT","maxWidth":480,"padding":20,"gap":24},"hero":{"composition":"CENTERED","avatarSize":72,"avatarRadius":36,"avatarBorder":0,"avatarShadow":"NONE","padding":16,"gap":6},"surface":{"variant":"OUTLINE","color":"#ffffff","borderColor":"#cbd0d5","borderWidth":1,"radius":8,"shadow":"NONE"},"action":{"minHeight":52,"padding":14,"iconSize":20,"textColor":"#20252b"},"typography":{"body":{"font":"SANS","color":"#20252b","size":16,"lineHeight":1.5},"name":{"font":"SANS","size":26,"weight":"600","lineHeight":1.2},"heading":{"font":"SANS","size":18,"weight":"600","lineHeight":1.35},"label":{"size":16,"weight":"500","color":"#20252b","lineHeight":1.35},"caption":{"size":13,"color":"#59616b","lineHeight":1.45}},"socials":{"surface":{"variant":"TRANSPARENT"},"action":{"iconColor":"#374151","iconSize":22}}}),
  preset("Premium Glass",{"version":1,"canvas":{"background":"GRADIENT","color":"#102e2d","gradientColor":"#35584d","appearance":"DARK","maxWidth":480,"padding":24,"gap":24},"hero":{"composition":"COVER_OVERLAP","avatarSize":120,"avatarRadius":60,"avatarBorder":2,"avatarBorderColor":"#e4e7dc","height":240,"overlap":54,"padding":24,"gap":8},"surface":{"variant":"GLASS","color":"#ffffff","opacity":22,"borderColor":"#93afa3","borderWidth":1,"radius":16,"blur":8},"action":{"minHeight":60,"padding":18,"iconSize":22,"textColor":"#ffffff"},"typography":{"body":{"font":"SANS","color":"#f5f7f3","size":16,"lineHeight":1.6},"name":{"font":"SERIF","size":32,"weight":"500","color":"#ffffff","lineHeight":1.2},"heading":{"font":"SANS","size":18,"weight":"600","color":"#f5f7f3","lineHeight":1.35},"label":{"size":16,"color":"#ffffff","lineHeight":1.35},"caption":{"size":13,"color":"#dce6df","lineHeight":1.45}},"primaryAction":{"surface":{"variant":"SOLID","color":"#e4e7dc","opacity":100,"radius":16,"borderWidth":0,"blur":0},"action":{"textColor":"#183631"}},"socials":{"surface":{"variant":"TRANSPARENT"},"action":{"iconColor":"#f5f7f3","iconSize":24}}}),
  preset("Warm Business",{"version":1,"canvas":{"background":"SOLID","color":"#f6eee2","appearance":"LIGHT","maxWidth":480,"padding":24,"gap":24},"hero":{"composition":"COVER_OVERLAP","height":220,"avatarSize":96,"avatarRadius":12,"avatarBorder":2,"avatarBorderColor":"#d6bc98","avatarShadow":"NONE","overlap":32,"padding":24,"gap":8},"surface":{"variant":"SOLID","color":"#fffcf7","radius":12,"borderWidth":1,"borderColor":"#d6bc98","shadow":"NONE"},"action":{"minHeight":60,"padding":18,"iconSize":22,"textColor":"#513624"},"typography":{"body":{"font":"SANS","color":"#513624","size":16,"lineHeight":1.6},"name":{"font":"SERIF","size":32,"weight":"500","lineHeight":1.2},"heading":{"font":"SERIF","size":22,"weight":"500","lineHeight":1.35},"label":{"font":"SANS","size":16,"color":"#513624","lineHeight":1.35},"caption":{"size":13,"color":"#72553d","lineHeight":1.45}},"primaryAction":{"surface":{"color":"#79482d","variant":"SOLID"},"action":{"textColor":"#ffffff"}},"socials":{"surface":{"variant":"TRANSPARENT"},"action":{"iconColor":"#79482d","iconSize":22}}}),
  preset("Dark Premium",{"version":1,"canvas":{"background":"SOLID","color":"#101518","appearance":"DARK","maxWidth":480,"padding":20,"gap":24},"hero":{"composition":"IMAGE_HERO","align":"LEFT","height":280,"avatarSize":88,"avatarRadius":8,"avatarBorder":1,"avatarBorderColor":"#91a3aa","avatarShadow":"NONE","overlayColor":"#000000","overlayOpacity":65,"padding":20,"gap":8},"surface":{"variant":"SOLID","color":"#202a2f","borderWidth":1,"borderColor":"#53636c","radius":6,"shadow":"NONE"},"action":{"minHeight":56,"padding":16,"iconSize":22,"textColor":"#f4f6f7"},"typography":{"body":{"font":"SANS","color":"#f4f6f7","size":16,"lineHeight":1.5},"name":{"font":"SANS","size":30,"weight":"700","tracking":0.4,"lineHeight":1.2},"heading":{"font":"SANS","size":20,"weight":"700","color":"#f4f6f7","lineHeight":1.35},"label":{"size":16,"weight":"600","color":"#f4f6f7","lineHeight":1.35},"caption":{"size":13,"color":"#c1cdd2","lineHeight":1.45}},"socials":{"surface":{"variant":"TRANSPARENT"},"action":{"iconColor":"#f4f6f7","iconSize":24}}}),
  preset("Bold Creator",{"version":1,"canvas":{"background":"SOLID","color":"#f4eefb","appearance":"LIGHT","maxWidth":480,"padding":20,"gap":24},"hero":{"composition":"CENTERED","avatarSize":112,"avatarRadius":56,"avatarBorder":0,"avatarShadow":"NONE","padding":24,"gap":10},"surface":{"variant":"OUTLINE","color":"#ffffff","borderColor":"#b6a0ce","borderWidth":1,"radius":20,"shadow":"NONE"},"action":{"minHeight":56,"padding":16,"iconSize":22,"textColor":"#42216b"},"typography":{"body":{"font":"SANS","color":"#302040","size":16,"lineHeight":1.5},"name":{"font":"SANS","size":36,"weight":"800","tracking":-0.5,"lineHeight":1.2},"heading":{"font":"SANS","size":22,"weight":"700","color":"#42216b","lineHeight":1.35},"label":{"size":16,"weight":"600","color":"#42216b","lineHeight":1.35},"caption":{"size":13,"color":"#675477","lineHeight":1.45}},"primaryAction":{"surface":{"variant":"SOLID","color":"#602c96","opacity":100,"radius":24,"borderWidth":0},"action":{"minHeight":68,"textColor":"#ffffff"}},"socials":{"surface":{"variant":"TRANSPARENT"},"action":{"iconColor":"#602c96","iconSize":26}}}),
  preset("Clean Professional",{"version":1,"canvas":{"background":"SOLID","color":"#edf1f5","appearance":"LIGHT","maxWidth":480,"padding":24,"gap":24},"hero":{"composition":"MINIMAL","align":"LEFT","avatarSize":64,"avatarRadius":8,"avatarBorder":0,"avatarShadow":"NONE","padding":20,"gap":6},"surface":{"variant":"SOLID","color":"#ffffff","borderWidth":1,"borderColor":"#d4dde5","radius":8,"shadow":"SOFT"},"action":{"minHeight":52,"padding":14,"iconSize":20,"textColor":"#183047"},"typography":{"body":{"font":"SANS","color":"#183047","size":16,"lineHeight":1.5},"name":{"font":"SANS","size":28,"weight":"600","lineHeight":1.2},"heading":{"font":"SERIF","size":20,"weight":"500","color":"#183047","lineHeight":1.35},"label":{"size":16,"color":"#183047","lineHeight":1.35},"caption":{"size":13,"color":"#506578","lineHeight":1.45}},"socials":{"surface":{"variant":"TRANSPARENT"},"action":{"iconColor":"#294357","iconSize":20}}}),
];
export function applyProfilePreset(current:ProfileDesign,visual?:ProfileVisual):ProfileDesign {
  const next:ProfileVisual=visual?structuredClone(visual):{version:1};
  const content=current.visual?.hero;
  if(content)next.hero={...next.hero,tagline:content.tagline,description:content.description,showBusinessType:content.showBusinessType};
  return {...current,visual:next};
}
