"use client";
import {useState} from "react";
import Image from "next/image";
import {editableVisual,type ProfileDesign} from "@/lib/profile-design";
import {applyBackgroundRecipe,backgroundRecipes} from "@/lib/background-recipes";
import {supportsBackgroundBlur,backgroundTextContrast,repairBackgroundTextContrast} from "@/lib/profile-presentation";
import {ColorPicker} from "@/components/ui/ColorPicker";
import {Upload} from "./V2Controls";
import {VisualChoice,ExactNumber} from "./VisualControls";
export const gradientDirections=[{symbol:"↖",angle:315,label:"Up left"},{symbol:"↑",angle:0,label:"Up"},{symbol:"↗",angle:45,label:"Up right"},{symbol:"←",angle:270,label:"Left"},{symbol:"→",angle:90,label:"Right"},{symbol:"↙",angle:225,label:"Down left"},{symbol:"↓",angle:180,label:"Down"},{symbol:"↘",angle:135,label:"Down right"}];
export function BackgroundEditor({design,onChange,organizationId,backgroundUrl,coverUrl,onBackgroundChange}:{design:ProfileDesign;onChange:(d:ProfileDesign)=>void;organizationId:string;backgroundUrl:string|null;coverUrl:string|null;onBackgroundChange:(url:string|null)=>void}){
 const visual=editableVisual(design),canvas=visual.canvas??{},[browse,setBrowse]=useState(false),contrast=backgroundTextContrast(design);
 const mode=browse||canvas.background==="EXISTING"||!canvas.background?"PRESETS":canvas.background;
 const patch=(next:Partial<typeof canvas>)=>onChange({...design,backgroundPreset:undefined,visual:{...visual,canvas:{...canvas,...next}}});
 function choose(next:string){setBrowse(next==="PRESETS");if(next!=="PRESETS")patch({background:next as "SOLID"|"GRADIENT"|"IMAGE",...(next==="GRADIENT"?{color:canvas.color??"#ffffff",gradientColor:canvas.gradientColor??"#dce5ef",gradientAngle:canvas.gradientAngle??135}:{})})}
 return <section className="builder-v3-card space-y-4"><h3>Background</h3><VisualChoice label="Background" value={mode} options={[{value:"SOLID",label:"Solid"},{value:"GRADIENT",label:"Gradient"},{value:"PRESETS",label:"Presets"},{value:"IMAGE",label:"Photo"}]} onChange={choose}/>
 {mode==="SOLID"&&<ColorPicker label="Color" value={canvas.color??"#ffffff"} onChange={color=>patch({color})}/>}
 {mode==="GRADIENT"&&<><div className="grid gap-4 sm:grid-cols-2"><ColorPicker label="Color 1" value={canvas.color??"#ffffff"} onChange={color=>patch({color})}/><ColorPicker label="Color 2" value={canvas.gradientColor??"#dce5ef"} onChange={gradientColor=>patch({gradientColor})}/></div><fieldset><legend className="mb-2 text-sm font-semibold">Direction</legend><div className="grid w-36 grid-cols-3 gap-1">{gradientDirections.map((d,index)=><button key={d.angle} type="button" aria-label={`Gradient direction ${d.label}`} aria-pressed={(canvas.gradientAngle??135)===d.angle} style={index===4?{gridColumn:3}:undefined} className="rounded-lg border border-[var(--admin-border)] p-2 text-lg aria-pressed:border-emerald-600 aria-pressed:bg-emerald-600/10" onClick={()=>patch({gradientAngle:d.angle})}>{d.symbol+"\uFE0E"}</button>)}</div></fieldset><details><summary className="cursor-pointer text-sm font-semibold">Advanced</summary><div className="mt-3"><ExactNumber label="Angle" value={canvas.gradientAngle??135} min={0} max={360} onChange={gradientAngle=>patch({gradientAngle})}/></div></details></>}
 {mode==="PRESETS"&&<><div className="grid grid-cols-4 gap-2">{backgroundRecipes.map(recipe=><button type="button" key={recipe.name} aria-label={`Background preset ${recipe.name}`} aria-pressed={recipe.named?canvas.background==="EXISTING"&&design.backgroundPreset===recipe.named:canvas.background==="GRADIENT"&&canvas.color===recipe.canvas?.color&&canvas.gradientColor===recipe.canvas?.gradientColor&&canvas.gradientAngle===recipe.canvas?.gradientAngle} className="min-w-0 rounded-lg border border-[var(--admin-border)] p-1 text-xs aria-pressed:border-emerald-600" onClick={()=>onChange(applyBackgroundRecipe({...design,visual},recipe))}><span aria-hidden="true" className="mb-1 block h-12 rounded" style={{background:recipe.preview}}/>{recipe.name}</button>)}</div><p className="builder-v3-note">Simple presets can be adjusted in Solid or Gradient. Aurora, Pearl, Dusk, Midnight, Mesh and Diffusion retain their fixed layered treatment.</p>{(!canvas.background||canvas.background==="EXISTING")&&!design.backgroundPreset&&<p className="builder-v3-note">Your existing background stays unchanged until you choose a look.</p>}</>}
 {mode==="IMAGE"&&<><VisualChoice label="Photo source" value={canvas.imageSource??"BACKGROUND"} options={[{value:"BACKGROUND",label:"Background photo"},...(coverUrl?[{value:"COVER",label:"Cover image"}]:[])]} onChange={imageSource=>patch({imageSource:imageSource as "BACKGROUND"|"COVER"})}/>{(canvas.imageSource==="COVER"?coverUrl:backgroundUrl)&&<Image unoptimized src={(canvas.imageSource==="COVER"?coverUrl:backgroundUrl)!} alt="Background preview" width={320} height={180} className="h-32 w-full rounded-lg object-cover"/>}{canvas.imageSource!=="COVER"&&<><Upload organizationId={organizationId} label={backgroundUrl?"Replace background photo":"Upload background photo"} onUploaded={async asset=>onBackgroundChange(asset.url)}/>{backgroundUrl&&<button type="button" className="builder-v3-delete" onClick={()=>onBackgroundChange(null)}>Remove background photo</button>}</>}<p className="builder-v3-note">Uses this profile’s photo. Publish changes with Save Changes.</p></>}
 {supportsBackgroundBlur(design)&&<label className="block text-sm font-medium">Background Blur <span className="float-right tabular-nums">{canvas.backgroundBlur??0}%</span><input aria-label="Background Blur" aria-valuetext={`${canvas.backgroundBlur??0}%`} type="range" min={0} max={100} step={1} value={canvas.backgroundBlur??0} className="mt-2 w-full accent-emerald-600" onChange={e=>onChange({...design,visual:{...visual,canvas:{...canvas,backgroundBlur:Number(e.target.value)}}})}/><span className="flex justify-between text-xs font-normal text-[var(--admin-text-secondary)]"><span>0%</span><span>100%</span></span></label>}
 {mode==="IMAGE"&&<details><summary className="cursor-pointer text-sm font-semibold">Advanced photo settings</summary><div className="mt-3 space-y-4"><ExactNumber label="Photo shading" value={canvas.overlayOpacity??0} max={90} onChange={overlayOpacity=>patch({overlayOpacity})}/><ColorPicker label="Shade color" value={canvas.overlayColor??"#000000"} onChange={overlayColor=>patch({overlayColor})}/><VisualChoice label="Photo fit" value={canvas.imageFit??"COVER"} options={[{value:"COVER",label:"Fill"},{value:"CONTAIN",label:"Fit"},{value:"AUTO",label:"Natural"}]} onChange={imageFit=>patch({imageFit:imageFit as typeof canvas.imageFit})}/><ExactNumber label="Photo horizontal position" value={canvas.focalX??50} onChange={focalX=>patch({focalX})}/><ExactNumber label="Photo vertical position" value={canvas.focalY??50} onChange={focalY=>patch({focalY})}/><p className="builder-v3-note">Use shading to keep foreground text readable. Blur reduces detail but does not replace contrast.</p></div></details>}
 {contrast?.low&&<div role="status" className="rounded-lg border border-amber-500/40 p-3 text-sm"><p>Some profile text may be hard to read on this background. Custom colors are preserved.</p><button type="button" className="mt-2 font-semibold underline" onClick={()=>onChange(repairBackgroundTextContrast(design))}>Use readable profile text colors</button><p className="builder-v3-note">Updates shared name, heading, body and footer text colors. Section and item customizations stay unchanged; check them in Preview.</p></div>}
 </section>;
}
