"use client";
import type {ProfileVisual} from "@/lib/profile-visual";
import {Field,Toggle} from "./V2Controls";
import {ExactNumber,VisualChoice} from "./VisualFields";

export function CardDetails({visual,onChange}:{visual:ProfileVisual;onChange:(next:Partial<ProfileVisual>)=>void}){
 const s=visual.surface??{},a=visual.action??{};
 const surface=(next:Partial<typeof s>)=>onChange({surface:{...s,...next}});
 const action=(next:Partial<typeof a>)=>onChange({action:{...a,...next}});
 return <div className="space-y-4">
  <details hidden={s.variant==="OUTLINE"||s.variant==="TRANSPARENT"}><summary className="cursor-pointer font-medium">Card fill</summary><div className="space-y-3 pt-3"><ExactNumber label="Fill strength" value={s.opacity??100} onChange={opacity=>surface({opacity})}/>{s.variant==="GLASS"&&<ExactNumber label="Background blur" value={s.blur??12} max={24} onChange={blur=>surface({blur})}/>}<Toggle label="Two-color fill" value={!!s.gradientColor} onChange={enabled=>surface({gradientColor:enabled?"#17181a":undefined})}/>{s.gradientColor&&<><Field type="color" label="Second fill color" value={s.gradientColor} onChange={gradientColor=>surface({gradientColor})}/><details><summary className="cursor-pointer text-sm">Advanced fill direction</summary><ExactNumber label="Fill direction" value={s.gradientAngle??135} max={360} onChange={gradientAngle=>surface({gradientAngle})}/></details></>}</div></details>
  <details><summary className="cursor-pointer font-medium">Border &amp; depth</summary><div className="space-y-3 pt-3"><ExactNumber label="Border thickness" value={s.borderWidth??0} max={4} onChange={borderWidth=>surface({borderWidth})}/>{(s.borderWidth??0)>0&&<Field type="color" label="Border color" value={s.borderColor??"#d4d4d4"} onChange={borderColor=>surface({borderColor})}/>}<VisualChoice label="Shadow" value={s.shadow??"NONE"} options={[{value:"NONE",label:"None"},{value:"SOFT",label:"Soft"},{value:"LIFTED",label:"Elevated"}]} onChange={shadow=>surface({shadow:shadow as typeof s.shadow})}/></div></details>
  <details><summary className="cursor-pointer font-medium">Icon tile</summary><div className="space-y-3 pt-3"><VisualChoice label="Icon placement" value={a.iconPosition??"LEFT"} options={[{value:"LEFT",label:"Left"},{value:"RIGHT",label:"Right"},{value:"TOP",label:"Above label"},{value:"TILE",label:"Tile"},{value:"NONE",label:"Hidden"}]} onChange={iconPosition=>action({iconPosition:iconPosition as typeof a.iconPosition})}/>{a.iconPosition!=="NONE"&&<><Toggle label="Multicolor brand artwork" value={a.brandArtwork??false} onChange={brandArtwork=>action({brandArtwork})}/><Field type="color" label="Icon tile background" value={a.iconBackground??"#29282b"} onChange={iconBackground=>action({iconBackground})}/>{a.iconBackground&&<button type="button" onClick={()=>action({iconBackground:undefined})}>No tile background</button>}<p className="builder-v3-note">Branded artwork can include its own signature color treatment.</p><details><summary className="cursor-pointer text-sm">Advanced tile dimensions</summary><div className="space-y-3 pt-3"><ExactNumber label="Icon tile size" value={a.iconContainerSize??24} min={24} max={72} onChange={iconContainerSize=>action({iconContainerSize})}/><ExactNumber label="Icon size" value={a.iconSize??24} min={16} max={48} onChange={iconSize=>action({iconSize})}/><ExactNumber label="Icon tile corners" value={a.iconRadius??14} max={36} onChange={iconRadius=>action({iconRadius})}/></div></details></>}</div></details>
  <details><summary className="cursor-pointer font-medium">Arrow</summary><div className="space-y-3 pt-3"><Toggle label="Show arrow" value={a.chevron??false} onChange={chevron=>action({chevron})}/>{a.chevron&&<details><summary className="cursor-pointer text-sm">Advanced arrow appearance</summary><div className="space-y-3 pt-3"><ExactNumber label="Arrow size" value={a.chevronSize??18} min={12} max={32} onChange={chevronSize=>action({chevronSize})}/><Field type="color" label="Arrow color" value={a.chevronColor??a.textColor??"#ffffff"} onChange={chevronColor=>action({chevronColor})}/></div></details>}</div></details>
  <details><summary className="cursor-pointer font-medium">Advanced dimensions</summary><div className="space-y-3 pt-3"><ExactNumber label="Inside padding" value={a.padding??16} min={8} max={32} onChange={padding=>action({padding})}/></div></details>
 </div>;
}
