"use client";
import {useRef,useState} from "react";
import Image from "next/image";
import {itemConfigs,type V2Item,type V2Link} from "@/lib/profile-v2";
import {Field,Upload,MediaControls} from "./V2Controls";
import {VisualChoice,ElementVisualControls} from "./VisualControls";
import {SortableList} from "./SortableList";
import {FiPlus,FiTrash2} from "./BuilderIcons";

const kinds={HEADING:"Heading",TEXT:"Text",LINK:"Button",IMAGE:"Image",CAROUSEL:"Gallery",DIVIDER:"Divider",SPACER:"Spacer",ICON_TEXT:"Icon / text callout"} as const;
type ContentKind=keyof typeof kinds;
const newId=()=>`new-${crypto.randomUUID()}`;
export function CustomContentDraftEditor({items,links=[],organizationId,onChange}:{items:V2Item[];links?:V2Link[];organizationId:string;onChange:(items:V2Item[])=>void}){
  const [kind,setKind]=useState<ContentKind>("TEXT"),[advanced,setAdvanced]=useState(false),[showChooser,setShowChooser]=useState(false);
  const latest=useRef(items);latest.current=items;
  const commit=(rows:V2Item[])=>{latest.current=rows;onChange(rows)};
  const update=(id:string,fn:(item:V2Item)=>V2Item)=>{if(!latest.current.some(item=>item.id===id))throw new Error("This item was removed before its upload finished.");commit(latest.current.map(item=>item.id===id?fn(item):item));};
  const add=(nextKind=kind)=>commit([...latest.current,{id:newId(),kind:nextKind,position:latest.current.length,width:"FULL",isVisible:true,config:itemConfigs[nextKind].parse({}),referencedProfileLinkId:null,images:[]}]);
  const chooser=<div className="flex flex-wrap items-end gap-3"><label className="text-sm space-y-2"><span className="block">Content type</span><select className="rounded-lg border bg-[var(--admin-input)] p-2" value={kind} onChange={event=>setKind(event.target.value as ContentKind)}>{Object.entries(kinds).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button type="button" className="builder-v3-add-link" onClick={()=>add()}><FiPlus size={16} aria-hidden="true"/> Add content</button><button type="button" className="text-sm" onClick={()=>setAdvanced(value=>!value)}>{advanced?"Hide advanced":"Advanced"}</button>{advanced&&<><button type="button" onClick={()=>{const id=newId();commit([...latest.current,{id,kind:"TEXT",position:latest.current.length,width:"FULL",isVisible:true,config:itemConfigs.TEXT.parse({testimonial:{author:""}}),referencedProfileLinkId:null,images:[]}])}}><FiPlus size={16} aria-hidden="true"/> Testimonial</button><button type="button" onClick={()=>add("LINK")}><FiPlus size={16} aria-hidden="true"/> Reuse saved link</button></>}</div>;
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><h3>Content</h3><button type="button" className="builder-v3-add-link" onClick={()=>setShowChooser(value=>!value)}><FiPlus size={16} aria-hidden="true"/> Add content</button></div>{showChooser&&chooser}
    <SortableList items={items} chromeIcons fallbackControls={false} label={item=>String(item.config.text||item.config.label||kinds[item.kind as ContentKind]||"Content")} onOrder={rows=>commit(rows.map((row,position)=>({...row,position})))}>
      {item=><div className="space-y-4 py-2"><div className="flex items-center justify-between gap-2"><strong>{kinds[item.kind as ContentKind]??"Existing content"}{!!item.config.visual&&<span className="builder-v3-override-badge ml-2">Item style</span>}</strong><label className="text-sm"><input type="checkbox" checked={item.isVisible} onChange={event=>update(item.id,row=>({...row,isVisible:event.target.checked}))}/> Show item</label></div>
        {["HEADING","TEXT","ICON_TEXT"].includes(item.kind)&&<><Field label={item.kind==="HEADING"?"Heading":"Text"} multiline={item.kind!=="HEADING"} value={String(item.config.text??"")} onChange={text=>update(item.id,row=>({...row,config:{...row.config,text}}))}/>{item.kind==="ICON_TEXT"&&<VisualChoice label="Icon" value={String(item.config.icon??"STAR")} options={["STAR","HEART","CHECK","PIN"].map(value=>({value,label:value.charAt(0)+value.slice(1).toLowerCase()}))} onChange={icon=>update(item.id,row=>({...row,config:{...row.config,icon}}))}/>}</>}
        {item.kind==="LINK"&&<><Field label="Button label" value={String(item.config.label??"")} onChange={label=>update(item.id,row=>({...row,config:{...row.config,label}}))}/><details className="builder-v3-advanced"><summary>Reuse saved link</summary><label className="block space-y-2 text-sm">Destination<select className="w-full rounded-lg border bg-[var(--admin-input)] p-2" value={item.referencedProfileLinkId??""} onChange={event=>update(item.id,row=>({...row,referencedProfileLinkId:event.target.value||null}))}><option value="">Custom URL</option>{links.filter(link=>link.isActive&&!link.id.startsWith("new-")).map(link=><option key={link.id} value={link.id}>{link.label||link.type}</option>)}</select></label></details>{!item.referencedProfileLinkId&&<Field label="Destination URL" value={String(item.config.url??"")} onChange={url=>update(item.id,row=>({...row,config:{...row.config,url}}))}/>}</>}
        {item.kind==="SPACER"&&<VisualChoice label="Space" value={String(item.config.size??"MEDIUM")} options={[{value:"SMALL",label:"Small"},{value:"MEDIUM",label:"Medium"},{value:"LARGE",label:"Large"}]} onChange={size=>update(item.id,row=>({...row,config:{...row.config,size}}))}/>}
        {["IMAGE","CAROUSEL"].includes(item.kind)&&!item.images.length&&<p className="builder-v3-note">This {item.kind==="CAROUSEL"?"gallery":"image"} has no photos yet and will not appear publicly. Add {item.kind==="CAROUSEL"?"gallery images":"an image"} below.</p>}
        {["IMAGE","CAROUSEL"].includes(item.kind)&&<><MediaControls simple carousel={item.kind==="CAROUSEL"} config={item.config} onChange={config=>update(item.id,row=>({...row,config}))}/><SortableList items={item.images} chromeIcons fallbackControls={false} label={image=>image.alt||image.caption||"Image"} onOrder={images=>update(item.id,row=>({...row,images:images.map((image,position)=>({...image,position}))}))}>{image=><div className="space-y-3 py-2"><Image unoptimized src={image.url} width={320} height={180} alt={image.alt||"Image preview"} className="h-32 w-full rounded-lg object-contain"/><Upload organizationId={organizationId} label="Replace image" onUploaded={async asset=>update(item.id,row=>({...row,images:row.images.map(current=>current.id===image.id?{...current,assetId:asset.id,url:asset.url}:current)}))}/><details><summary className="cursor-pointer text-sm font-semibold">More options</summary><div className="space-y-3 pt-3"><Field label="Alt text" value={image.alt} onChange={alt=>update(item.id,row=>({...row,images:row.images.map(current=>current.id===image.id?{...current,alt}:current)}))}/><Field label="Caption" value={image.caption??""} onChange={caption=>update(item.id,row=>({...row,images:row.images.map(current=>current.id===image.id?{...current,caption:caption||null}:current)}))}/><Field label="Image destination URL" value={image.destinationUrl??""} onChange={destinationUrl=>update(item.id,row=>({...row,images:row.images.map(current=>current.id===image.id?{...current,destinationUrl:destinationUrl||null}:current)}))}/></div></details><button type="button" className="builder-v3-delete" onClick={()=>{if(window.confirm("Remove this image from the draft? Save Changes applies the removal."))update(item.id,row=>({...row,images:row.images.filter(current=>current.id!==image.id)}))}}><FiTrash2 size={16} aria-hidden="true"/>Remove image</button></div>}</SortableList>{(item.kind==="CAROUSEL"||item.images.length===0)&&<Upload organizationId={organizationId} label={item.kind==="CAROUSEL"?"Add gallery images":"Add image"} multiple={item.kind==="CAROUSEL"} onUploaded={async asset=>update(item.id,row=>({...row,images:[...row.images,{id:newId(),assetId:asset.id,url:asset.url,position:row.images.length,alt:"",caption:null,destinationUrl:null}]}))}/>}</>}
        <details className="builder-v3-advanced"><summary>Customize this item</summary><div className="space-y-4 pt-3"><VisualChoice label="Width" value={item.width} options={[{value:"FULL",label:"Full"},{value:"HALF",label:"Half"}]} onChange={width=>update(item.id,row=>({...row,width}))}/>{["HEADING","TEXT","ICON_TEXT"].includes(item.kind)&&<ElementVisualControls scope="item" layout={false} action={false} config={item.config} onChange={config=>update(item.id,row=>({...row,config}))}/>} {item.kind==="TEXT"&&<><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!item.config.testimonial} onChange={event=>update(item.id,row=>{const config={...row.config};if(event.target.checked)config.testimonial={author:""};else delete config.testimonial;return {...row,config}})}/>Use testimonial attribution</label>{!!item.config.testimonial&&<><Field label="Author" value={String((item.config.testimonial as {author?:string}).author??"")} onChange={author=>update(item.id,row=>({...row,config:{...row.config,testimonial:{...(row.config.testimonial as object),author}}}))}/><Field label="Role" value={String((item.config.testimonial as {role?:string}).role??"")} onChange={role=>update(item.id,row=>({...row,config:{...row.config,testimonial:{...(row.config.testimonial as object),role}}}))}/></>}</>}{item.kind==="LINK"&&<ElementVisualControls scope="item" layout={false} action config={item.config} onChange={config=>update(item.id,row=>({...row,config}))}/>}</div></details>
        <button type="button" className="builder-v3-delete" onClick={()=>{if(window.confirm("Delete this item from the draft? Save Changes applies the deletion."))commit(latest.current.filter(row=>row.id!==item.id))}}><FiTrash2 size={16} aria-hidden="true"/>Delete item</button>
      </div>}
    </SortableList>
    {!showChooser&&chooser}
  </div>;
}
