"use client";
import {useState} from "react";
import {Field} from "./V2Controls";
import {VisualChoice,ExactNumber,ButtonStyle,TextAppearance} from "./VisualControls";
import {readVisual,type VisualText,type ProfileVisual,type VisualOverride} from "@/lib/profile-visual";
import type {V2Section} from "@/lib/profile-v2";
import {inheritedSectionConfig,sectionHasStyleOverride,type ThemeSnapshot} from "@/lib/custom-themes";
import {PresetNumber} from "./PrecisionControls";
import {SocialDetails} from "./SocialDetails";

export function LinkAppearance({value,global,onChange}:{value:(VisualOverride&{subtitle?:string})|undefined;global:VisualOverride;onChange:(value:(VisualOverride&{subtitle?:string})|undefined)=>void}){
  const merged={...global,...value,surface:{...global.surface,...value?.surface},action:{...global.action,...value?.action},text:{...global.text,...value?.text}};
  const change=(next:VisualOverride)=>{const result={...value};for(const group of ["surface","action","text"] as const){const changes=Object.fromEntries(Object.entries(next[group]??{}).filter(([key,v])=>v!==(merged[group] as Record<string,unknown>)[key]));if(Object.keys(changes).length)result[group]={...value?.[group],...changes};}onChange(result)};
  return <div className="space-y-4 pt-3"><p className="builder-v3-note">Only changed properties override the section and Global Design.</p><ButtonStyle arrow={false} value={merged} onChange={change}/><details><summary className="cursor-pointer text-sm">Link text</summary><div className="pt-3"><TextAppearance color={false} alignment={false} value={merged.text} onChange={text=>change({...merged,text})}/></div></details>{value&&(value.surface||value.action||value.text)&&<button type="button" onClick={()=>onChange(undefined)}>Reset local appearance</button>}</div>;
}

export function EssentialText({value,onChange,font=false,role="body",color=true,alignment=true}:{value:VisualText;onChange:(value:VisualText)=>void;font?:boolean;role?:"name"|"heading"|"body"|"label"|"caption";color?:boolean;alignment?:boolean}){
  const sizes={name:[24,30,36],heading:[16,20,24],body:[14,16,18],label:[14,16,20],caption:[12,14,16]}[role],size=value.size??sizes[1];
  return <div className="space-y-4">
    {font&&<VisualChoice label="Font" value={value.font??"SANS"} options={[{value:"SANS",label:"Modern"},{value:"SERIF",label:"Classic"},{value:"HUMANIST",label:"Friendly"},{value:"MONO",label:"Monospace"}]} onChange={font=>onChange({...value,font:font as VisualText["font"]})}/>}
    {alignment&&<VisualChoice label="Alignment" value={value.align??"LEFT"} options={[{value:"LEFT",label:"Left"},{value:"CENTER",label:"Center"},{value:"RIGHT",label:"Right"}]} onChange={align=>onChange({...value,align:align as VisualText["align"]})}/>}
    <PresetNumber label="Text size" value={size} presets={sizes.map((value,index)=>({value,label:["Small","Medium","Large"][index]}))} min={12} max={64} onChange={size=>onChange({...value,size})}/>
    <details><summary className="cursor-pointer text-sm">Advanced text settings</summary><div className="pt-3 space-y-3"><ExactNumber label="Line spacing" min={1.1} max={2} value={value.lineHeight??1.4} onChange={lineHeight=>onChange({...value,lineHeight})}/><ExactNumber label="Letter spacing" min={-1} max={4} value={value.tracking??0} onChange={tracking=>onChange({...value,tracking})}/></div></details>
    <details><summary className="cursor-pointer text-sm">Text weight</summary><VisualChoice label="Weight" value={value.weight??"400"} options={[{value:"400",label:"Regular"},{value:"500",label:"Medium"},{value:"600",label:"Semibold"},{value:"700",label:"Bold"},{value:"800",label:"Heavy"}]} onChange={weight=>onChange({...value,weight:weight as VisualText["weight"]})}/></details>
    {color&&<Field type="color" label="Text color" value={value.color??"#172033"} onChange={color=>onChange({...value,color})}/>}
  </div>;
}

export function EssentialButtons({value,onChange,textColor=true,showSize=true}:{value:VisualOverride;onChange:(value:VisualOverride)=>void;textColor?:boolean;showSize?:boolean}){
  const surface=value.surface??{},action=value.action??{};
  return <div className="space-y-4">
    <VisualChoice label="Card style" value={surface.variant??"SOFT"} options={[{value:"TRANSPARENT",label:"No fill"},{value:"SOFT",label:"Soft fill"},{value:"SOLID",label:"Filled"},{value:"OUTLINE",label:"Outline"},{value:"GLASS",label:"Glass"}]} onChange={variant=>onChange({...value,surface:{...surface,variant:variant as typeof surface.variant,opacity:variant==="GLASS"?24:variant==="SOFT"?12:100}})}/>
    {surface.variant!=="TRANSPARENT"&&<Field type="color" label="Card color" value={surface.color??"#ffffff"} onChange={color=>onChange({...value,surface:{...surface,color}})}/>}
    {textColor&&<Field type="color" label="Link text color" value={action.textColor??"#172033"} onChange={textColor=>onChange({...value,action:{...action,textColor}})}/>}
    <PresetNumber label="Card corners" value={surface.radius??16} presets={[{value:0,label:"Square"},{value:8,label:"Soft"},{value:16,label:"Rounded"},{value:48,label:"Pill"}]} max={48} onChange={radius=>onChange({...value,surface:{...surface,radius}})}/>
    {showSize&&<PresetNumber label="Size" value={action.minHeight??56} presets={[{value:48,label:"Small"},{value:60,label:"Medium"},{value:72,label:"Large"}]} min={44} max={160} onChange={minHeight=>onChange({...value,action:{...action,minHeight}})}/>}
  </div>;
}

export function EssentialSectionAppearance({section,global,onChange,theme}:{section:V2Section;global:ProfileVisual;theme?:ThemeSnapshot;onChange:(section:V2Section)=>void}){
  const [customSpaceFor,setCustomSpaceFor]=useState<string|null>(null),[customizingSection,setCustomizingSection]=useState<string|null>(null);
  const visual=readVisual(section.config.visual),overridden=sectionHasStyleOverride(section,theme),customized=customizingSection===section.id||(section.kind!=="SOCIALS"&&overridden);
  const setVisual=(next:VisualOverride|undefined)=>onChange({...section,config:{...section.config,visual:next}});
  const patchGroup=<K extends keyof VisualOverride>(group:K,value:NonNullable<VisualOverride[K]>)=>setVisual({...visual,[group]:value});
  const globalButton:VisualOverride={surface:{...(section.kind==="SOCIALS"?global.socials?.surface:global.surface),...visual.surface},action:{...(section.kind==="SOCIALS"?global.socials?.action:global.action),...visual.action}};
  const changeButtons=(next:VisualOverride)=>{const result={...visual};for(const group of ["surface","action"] as const){const changed=Object.fromEntries(Object.entries(next[group]??{}).filter(([key,value])=>value!==(globalButton[group] as Record<string,unknown>|undefined)?.[key]));if(Object.keys(changed).length)result[group]={...visual[group],...changed};}setVisual(result)};
  const isSocial=section.kind==="SOCIALS";
  const socialSurface={...global.socials?.surface,...visual.surface};
  const socialDetail=<details><summary className="cursor-pointer text-sm font-medium">Outer social button surface</summary><div className="mt-3 space-y-3"><VisualChoice label="Button style" value={socialSurface.variant??"TRANSPARENT"} options={[{value:"TRANSPARENT",label:"No fill"},{value:"SOLID",label:"Filled"},{value:"GLASS",label:"Glass"}]} onChange={variant=>patchGroup("surface",{...visual.surface,variant:variant as typeof socialSurface.variant})}/>{socialSurface.variant!=="TRANSPARENT"&&<Field type="color" label="Outer button color" value={socialSurface.color??"#202023"} onChange={color=>patchGroup("surface",{...visual.surface,color})}/>}{socialSurface.variant!=="TRANSPARENT"&&<ExactNumber label="Outer button fill strength" value={socialSurface.opacity??100} onChange={opacity=>patchGroup("surface",{...visual.surface,opacity})}/>}{socialSurface.variant==="GLASS"&&<ExactNumber label="Outer button blur" max={24} value={socialSurface.blur??12} onChange={blur=>patchGroup("surface",{...visual.surface,blur})}/>}{(socialSurface.borderWidth??0)>0&&<Field type="color" label="Outer button border color" value={socialSurface.borderColor??"#74685d"} onChange={borderColor=>patchGroup("surface",{...visual.surface,borderColor})}/>}<VisualChoice label="Outer button shadow" value={socialSurface.shadow??"NONE"} options={[{value:"NONE",label:"None"},{value:"SOFT",label:"Soft"},{value:"LIFTED",label:"Elevated"}]} onChange={shadow=>patchGroup("surface",{...visual.surface,shadow:shadow as typeof socialSurface.shadow})}/></div></details>;
  const reset=()=>{setCustomizingSection(null);onChange({...section,config:inheritedSectionConfig(section,theme)})};
  return <section className="builder-v3-card space-y-5"><div className="flex items-center justify-between gap-3"><h3>Appearance</h3>{overridden&&<span className="builder-v3-override-badge">Section style</span>}</div><p className="builder-v3-note">Inherits the theme and Global Design. Only your changes override the inherited style.</p>
{isSocial&&<VisualChoice label="Presentation" value={String(section.config.composition??"ICONS")} options={[{value:"ICONS",label:"Icons"},{value:"CARDS",label:"Button Cards"}]} onChange={composition=>onChange({...section,config:{...section.config,composition}})}/>}
{isSocial&&<PresetNumber label="Social icon size" value={visual.action?.iconSize??({SMALL:20,MEDIUM:28,LARGE:36}[String(section.config.iconSize) as "SMALL"|"MEDIUM"|"LARGE"]??global.socials?.action?.iconSize??28)} min={16} max={48} presets={[{value:20,label:"Small"},{value:28,label:"Medium"},{value:36,label:"Large"}]} onChange={iconSize=>patchGroup("action",{...visual.action,iconSize})}/>}
{isSocial&&<><p className="builder-v3-note">Icon size changes the logo. Button size changes the clickable circle or card.</p><PresetNumber label="Social button size" value={visual.action?.minHeight??global.socials?.action?.minHeight??48} min={44} max={160} presets={[{value:44,label:"Small"},{value:48,label:"Medium"},{value:60,label:"Large"}]} onChange={minHeight=>patchGroup("action",{...visual.action,minHeight})}/></>}
{isSocial&&<><h4 className="text-sm font-semibold">Layout</h4><VisualChoice label="Alignment" value={String(section.config.align??"CENTER")} options={[{value:"LEFT",label:"Left"},{value:"CENTER",label:"Center"},{value:"RIGHT",label:"Right"}]} onChange={align=>onChange({...section,config:{...section.config,align}})}/>
<label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={section.config.labels===true} onChange={event=>onChange({...section,config:{...section.config,labels:event.target.checked}})}/>Show platform labels</label></>}
{isSocial&&<div className="space-y-3"><h4 className="text-sm font-semibold">Spacing</h4><VisualChoice label="Space above" value={customSpaceFor===section.id||visual.layout?.before!==undefined&&![0,8,16,24].includes(visual.layout.before)?"CUSTOM":visual.layout?.before===undefined?"INHERIT":String(visual.layout.before)} options={[{value:"INHERIT",label:`Use profile (${global.canvas?.gap??0}px)`},{value:"0",label:"None"},{value:"8",label:"Small"},{value:"16",label:"Medium"},{value:"24",label:"Large"},{value:"CUSTOM",label:"Custom"}]} onChange={before=>{setCustomSpaceFor(before==="CUSTOM"?section.id:null);if(before!=="CUSTOM"){const layout={...visual.layout};if(before==="INHERIT")delete layout.before;else layout.before=Number(before);patchGroup("layout",layout)}}}/>{(customSpaceFor===section.id||visual.layout?.before!==undefined&&![0,8,16,24].includes(visual.layout.before))&&<details open={customSpaceFor===section.id}><summary className="cursor-pointer text-sm">Custom space above</summary><ExactNumber label="Custom space above" min={0} max={80} value={visual.layout?.before??0} onChange={before=>patchGroup("layout",{...visual.layout,before})}/></details>}<p className="builder-v3-note">Space before this section only. Header inside spacing is unchanged.</p></div>}
<PresetNumber label={isSocial?(section.config.composition==="CARDS"?"Card gap":"Icon gap"):section.singletonKey==="LINKS"?"Space between links":"Section content spacing"} value={visual.layout?.gap??(isSocial?{COMPACT:2,COMFORTABLE:16,SPACIOUS:24}[String(section.config.spacing??"COMFORTABLE") as "COMPACT"|"COMFORTABLE"|"SPACIOUS"]:16)} max={40} presets={[{value:isSocial?2:8,label:"Compact"},{value:16,label:"Balanced"},{value:24,label:"Spacious"}]} onChange={gap=>patchGroup("layout",{...visual.layout,gap})}/>
    <label className="flex items-center gap-3"><input type="checkbox" checked={customized} onChange={event=>event.target.checked?setCustomizingSection(section.id):reset()}/>Customize this section</label>
    {!customized&&overridden&&<p className="builder-v3-note">This section has local appearance changes. Open Customize this section to edit or reset them.</p>}
    {customized&&<>
      {isSocial&&<>
        <h4 className="text-sm font-semibold">Logo appearance</h4><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={visual.action?.brandArtwork??global.socials?.action?.brandArtwork??false} onChange={event=>patchGroup("action",{...visual.action,brandArtwork:event.target.checked})}/>Multicolor brand artwork</label>

        <h4 className="text-sm font-semibold">Inner logo container</h4><p className="builder-v3-note">Wraps the logo inside the outer social button.</p><VisualChoice label="Icon background" value={String(section.config.containerStyle??"ICON_ONLY")} options={[{value:"ICON_ONLY",label:"No fill"},{value:"FILLED",label:"Filled"},{value:"BRANDED",label:"Platform brand fill"},{value:"OUTLINE",label:"Outline"}]} onChange={containerStyle=>onChange({...section,config:{...section.config,containerStyle}})}/>
        {["FILLED","OUTLINE"].includes(String(section.config.containerStyle))&&<Field type="color" label="Icon background color" value={String(section.config.containerColor??global.surface?.color??"#ffffff")} onChange={containerColor=>onChange({...section,config:{...section.config,containerColor}})}/>}
        {section.config.containerStyle==="BRANDED"&&section.config.composition!=="CARDS"?<p className="builder-v3-note">The platform background and a contrasting logo are applied automatically.</p>:<VisualChoice label="Logo color" value={String(section.config.iconColor??"INHERIT")} options={[{value:"INHERIT",label:"Use profile"},{value:"THEME",label:"Theme"},{value:"MONOCHROME",label:"Single color"},{value:"BRAND",label:"Platform logo colors"}]} onChange={iconColor=>{const action={...visual.action};if(iconColor!=="MONOCHROME")delete action.iconColor;onChange({...section,config:{...section.config,iconColor,visual:{...visual,action}}})}}/>}
        {(section.config.containerStyle??"ICON_ONLY")!=="ICON_ONLY"&&<VisualChoice label="Icon background shape" value={String(section.config.shape??"CIRCLE")} options={[{value:"CIRCLE",label:"Circle"},{value:"ROUNDED",label:"Rounded"},{value:"SQUARE",label:"Square"}]} onChange={shape=>onChange({...section,config:{...section.config,shape}})}/> }
        {(section.config.containerStyle??"ICON_ONLY")!=="ICON_ONLY"&&<label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={section.config.border===true} onChange={event=>onChange({...section,config:{...section.config,border:event.target.checked}})}/>Icon background border</label>}
        {section.config.composition!=="CARDS"&&<><h4 className="text-sm font-semibold">Social buttons</h4><details><summary className="cursor-pointer text-sm">Advanced social button settings</summary><SocialDetails showSize={false} value={{surface:socialSurface,action:{...global.socials?.action,...visual.action}}} onChange={changeButtons}/>{socialDetail}</details></>}

        
        
      </>}
      {!isSocial&&<p className="builder-v3-note">{section.singletonKey==="LINKS"||section.singletonKey==="BUSINESS_INFO"?"These settings change cards in this section only. Individual item styling takes priority.":"Shared section styling applies to the section container. Text, buttons and images are customized on their individual items."}</p>}
      {(isSocial||section.singletonKey==="LINKS")&&<details><summary className="cursor-pointer text-sm">Section background</summary><div className="pt-3"><VisualChoice label="Behind the buttons" value={String((section.config.surface as {preset?:string}|undefined)?.preset??"INHERIT")} options={[{value:"INHERIT",label:"Use profile"},{value:"NONE",label:"No background"},{value:"MINIMAL",label:"Minimal"},{value:"CARD",label:"Card"}]} onChange={preset=>onChange({...section,config:{...section.config,surface:{preset}}})}/><p className="builder-v3-note">The section wrapper only; individual button styles stay unchanged.</p></div></details>}
      {isSocial&&(section.config.containerStyle!=="BRANDED"||section.config.composition==="CARDS")&&section.config.iconColor==="MONOCHROME"&&<Field type="color" label="Single icon color" value={visual.action?.iconColor??global.socials?.action?.iconColor??"#172033"} onChange={iconColor=>onChange({...section,config:{...section.config,iconColor:"MONOCHROME",visual:{...visual,action:{...visual.action,iconColor}}}})}/>}
      {isSocial&&(section.config.containerStyle??"ICON_ONLY")!=="ICON_ONLY"&&section.config.border===true&&<Field type="color" label="Border color" value={String(section.config.borderColor??"#172033")} onChange={borderColor=>onChange({...section,config:{...section.config,borderColor}})}/>}
      {(section.singletonKey==="LINKS"||section.singletonKey==="BUSINESS_INFO"||isSocial&&section.config.composition==="CARDS")&&<EssentialButtons value={globalButton} onChange={changeButtons} showSize={!isSocial}/>}
      {section.kind==="CUSTOM"&&<><VisualChoice label="Section background style" value={visual.surface?.variant??"TRANSPARENT"} options={[{value:"TRANSPARENT",label:"None"},{value:"SOLID",label:"Filled"},{value:"GLASS",label:"Glass"},{value:"OUTLINE",label:"Outline"}]} onChange={variant=>patchGroup("surface",{...visual.surface,variant:variant as NonNullable<VisualOverride["surface"]>["variant"]})}/>{visual.surface?.variant&&visual.surface.variant!=="TRANSPARENT"&&<Field type="color" label="Section background" value={visual.surface?.color??global.surface?.color??"#ffffff"} onChange={color=>patchGroup("surface",{...visual.surface,color})}/>}</>}

      

      <p className="builder-v3-note">Reset restores this section’s inherited appearance, including local layout and spacing. Content, visibility and order stay unchanged.</p><div className="flex flex-wrap gap-3"><button type="button" onClick={reset}>Reset local appearance</button></div>
    </>}
  </section>;
}
